# Generated by Django 3.0.4 on 2020-08-05 11:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('trustees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trusteespage',
            name='about_content',
        ),
        migrations.AddField(
            model_name='trusteespage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='TrusteePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('trustee_name', models.CharField(max_length=150)),
                ('trustee_role', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Add email address', max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Linkedin URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube channel URL', null=True)),
                ('trustee_info', wagtail.core.fields.RichTextField()),
                ('trustee_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
