# Generated by Django 3.0.4 on 2020-08-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0002_auto_20200805_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trusteespage',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='trusteepage',
            name='trustee_name',
            field=models.CharField(max_length=110),
        ),
    ]
