# Generated by Django 3.0.4 on 2020-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0003_auto_20200806_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteepage',
            name='trustee_name',
            field=models.CharField(max_length=150),
        ),
    ]
