# Generated by Django 3.0.4 on 2020-08-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('trustees', '0005_genericpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericPage',
        ),
    ]
