# Generated by Django 3.0.4 on 2020-09-01 10:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0006_delete_genericpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteespage',
            name='content',
            field=wagtail.core.fields.StreamField([('text_with_button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['p', 'link', 'bold', 'italic'])), ('button_name', wagtail.core.blocks.CharBlock(help_text='Add text', max_length=100)), ('Button_link', wagtail.core.blocks.PageChooserBlock())]))], null=True),
        ),
    ]
