# Generated by Django 3.0.4 on 2020-08-30 09:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='content',
            field=wagtail.core.fields.StreamField([('Gofundme_link', wagtail.core.blocks.StructBlock([('donation_link', wagtail.core.blocks.TextBlock(help_text='Add gofundme donation page link', required=True))], max_num=1))]),
        ),
    ]
