# Generated by Django 3.0.4 on 2020-08-30 09:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20200830_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='content',
        ),
        migrations.AddField(
            model_name='donatepage',
            name='donation_link',
            field=wagtail.core.fields.StreamField([('donation_link', wagtail.core.blocks.TextBlock(help_text='Add gofundme donation page link', required=True))], null=True),
        ),
    ]
