# Generated by Django 3.0.4 on 2020-08-30 09:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20200830_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='donation_link',
            field=wagtail.core.fields.StreamField([('Gofundme_link', wagtail.core.blocks.StructBlock([('gofundme_link', wagtail.core.blocks.URLBlock(help_text='Add gofundme donation page link', required=True))]))], null=True),
        ),
    ]
