# Generated by Django 3.0.4 on 2020-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_auto_20200830_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='body',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='header',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
