# Generated by Django 3.0.4 on 2020-08-31 12:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_auto_20200830_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='donation_link',
            field=wagtail.core.fields.StreamField([('gofundme', wagtail.core.blocks.StructBlock([('gofundme_page_link', wagtail.core.blocks.URLBlock(help_text='Add gofundme donation page link.'))])), ('paypal', wagtail.core.blocks.StructBlock([('paypal_email', wagtail.core.blocks.EmailBlock(help_text='Add PayPal acount email'))]))], null=True),
        ),
    ]
