# Generated by Django 3.0.4 on 2020-09-01 07:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_auto_20200831_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='donation_link',
            field=wagtail.core.fields.StreamField([('gofundme', wagtail.core.blocks.StructBlock([('gofundme_page_link', wagtail.core.blocks.URLBlock(help_text='Add gofundme donation page link.'))])), ('paypal', wagtail.core.blocks.StructBlock([('paypal_email', wagtail.core.blocks.EmailBlock(help_text='Add PayPal acount email'))])), ('amazon_smile', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['p', 'bold', 'italic'])), ('amazon_smile_link', wagtail.core.blocks.URLBlock(help_text='Add Amazon Smile link'))]))], null=True),
        ),
    ]
