# Generated by Django 3.0.3 on 2020-08-11 12:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporters',
            name='intro',
        ),
        migrations.AddField(
            model_name='supporterspage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='page detail'),
        ),
    ]
