# Generated by Django 3.0.4 on 2020-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0002_auto_20200811_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporterspage',
            name='intro',
            field=models.CharField(blank=True, max_length=650),
        ),
    ]
