# Generated by Django 3.0.3 on 2020-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='beneficiary_link',
            field=models.URLField(null=True),
        ),
    ]
