# Generated by Django 3.0.3 on 2020-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiaries_beneficiary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
