# Generated by Django 3.0.4 on 2020-06-27 14:50

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200627_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_number',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
