# Generated by Django 3.0.4 on 2020-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200830_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='header',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
