# Generated by Django 3.0.4 on 2020-06-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
