# Generated by Django 3.0.4 on 2020-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomesupporterpage',
            name='contact_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
