# Generated by Django 3.0.4 on 2020-08-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_becomevolunteerpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomevolunteerpage',
            old_name='volunteer_info',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='becomevolunteerpage',
            old_name='volunteer_name',
            new_name='contact_name',
        ),
    ]
