# Generated by Django 3.0.4 on 2020-09-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('support', '0004_auto_20200816_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomesupporterpage',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='becomesupporterpage',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='becomesupporterpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='becomesupporterpage',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='becomevolunteerpage',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='becomevolunteerpage',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='becomevolunteerpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='becomevolunteerpage',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='becomesupporterpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='becomesupporterpage',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
