# Generated by Django 3.0.4 on 2020-09-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20200925_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomesupporterpage',
            old_name='page_link',
            new_name='button_link',
        ),
    ]
