# Generated by Django 3.0.4 on 2020-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200912_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='display_image_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'center'), ('bottom', 'bottom')], default='top', max_length=6),
        ),
    ]
