# Generated by Django 3.0.4 on 2020-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_display_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='display_image_position',
            field=models.CharField(choices=[('top', 'Top part'), ('center', 'Center part'), ('bottom', 'Bottom part')], default='top', max_length=6),
        ),
    ]
