# Generated by Django 3.0.4 on 2020-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200914_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='display_image_position',
            field=models.CharField(choices=[('top', 'Top part'), ('center', 'Center part'), ('bottom', 'Bottom part')], default='top', help_text='Adjust the positon of image displayed on article page cover', max_length=6),
        ),
    ]
