# Generated by Django 3.0.4 on 2020-08-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0004_auto_20200830_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
