# Generated by Django 3.0.4 on 2020-08-31 19:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200831_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheader',
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_link_1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_link_2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_1',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_2',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
