# Generated by Django 3.0.4 on 2020-09-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_content',
        ),
    ]
