# Generated by Django 3.0.4 on 2020-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_footersetting_pagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersetting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
