# Generated by Django 3.0.4 on 2020-09-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20200901_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageLink',
        ),
    ]
