# Generated by Django 3.0.4 on 2020-09-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_quicklinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickLinks',
        ),
    ]
